language: Java
jdk:
  - oraclejdk8
before_install:
  - pip install --user codecov

script: ./gradlew check --debug

after_success:
  - codecov

# coverity scan
env:
  global:
    - secure: "A+JodfRzulrwez5TVSm2k1SQPxsis68gM22JN4nqjm4RgekfHnfWe5OoLYhdFuhgyzkUE7AnmkhcZCtYpl4/hCtRs4pZ+Hum4vtSh99dLaMOW3CpUzaBpWPtCcuEN2DP3v8hMAkbqiaSEYxfKM94CH3Ct+YH8xuaMvcYsuBRaFz2KSJXnfor+111VGGjoDSRFqMd6cpq4m0U22vUtyCBVeu8+HPRn3ySyafL7hNCBNyZgkp1KZZPD6RgzHPbjVKA9lBO27CnSBsp3uWHv5Zfee80JFsjIECRhR5djYI/mq3xtWTsdnIOTEjiT8ahwpxJBrAscapt8iTmZolaYLoe97JLFcU4qQLQGsdg6SRcCbpiTFyu7oMqcApxdb+6er9I5B4XVN329xpTZLYsMFZAzeqhZswYxAJiRPIzS79y/WFBNMwlHPHYZauAMZTPiWK/+8sr3hyrtSyuzMms3puBAAvjfDKWI4QOIoVMUxp+O3gTHi29/UpegFwgEOMYXd2CspQROx76zq0G5xGeGK5FSRnvaE27VKPKlBdyE9DT8AZxy1sP9pigHCt4E/dV+4lM5awCCCqCVP5//yFrCFiTb0vINkZjYOhuaqckkAeKRa8/yZnGeXbZ4ENL+ZqVL/PnOdqd4jCS3uTSuW2s4N5AC7bXtCuHtiEWNj/siEzndE0="
addons:
  coverity_scan:

    project:
      name: spolnik/trading-office
      version: 1.0
      description: Trading Office

    notification_email: jacek.spolnik@gmail.com

    build_command_prepend: ""

    build_command: "./gradlew build"

    branch_pattern: coverity_scan

branches:
  only:
    - master
    - coverity_scan
    - heroku-allocation-message-translator
    - heroku-confirmation-sender
    - heroku-confirmation-service
    - heroku-instruments-service
    - heroku-finance-data-service